---
- name: Cisco Switch Read-Only Test
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    ansible_network_cli_ssh_type: libssh
    ansible_ssh_common_args: '-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa -o Ciphers=+aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc'
  tasks:
    - name: Execute 'show version' command
      cisco.ios.ios_command:
        commands:
          - show version
      register: switch_output

    - name: Display the result on AWX Dashboard
      debug:
        msg: "{{ switch_output.stdout[0] }}"