---
- name: Cisco Switch Read-Only Test
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
  tasks:
    - name: Execute 'show version' command
      cisco.ios.ios_command:
        commands:
          - show version
      register: switch_output

    - name: Display the result on AWX Dashboard
      debug:
        msg: "{{ switch_output.stdout[0] }}"